# Generated by Django 3.1.4 on 2020-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='time',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu\\static\\menu\\images'),
        ),
    ]
