# Generated by Django 3.1.4 on 2020-12-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20201205_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu\\static\\menu\\images'),
        ),
    ]
