# Generated by Django 3.1.4 on 2020-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201205_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='time',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('Hot Sandwhiches', 'Hot Sandwhiches'), ('Cold Sandwhiches', 'Cold Sandwhiches'), ('Entress', 'Entress')], db_index=True, default=None, max_length=100),
        ),
    ]
