# Generated by Django 3.1.4 on 2020-12-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20201207_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
    ]
