# Generated by Django 3.1.4 on 2020-12-08 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsofTheWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Burger', 'burger'), ('Dessert', 'Dessert')], db_index=True, default=None, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
