# Generated by Django 3.2a1 on 2021-02-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20201230_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsoftheweek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\menu\\images'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\menu\\images'),
        ),
    ]
